# Site settings
title: I Am Hypatia
header-img: img/home-bg.png
email: yolandafay@gmail.com
copyright_name: YolandaFay
description: > # this means to ignore newlines until "baseurl:"
  For the Love of Literature, Mathematics, and Coding
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  YolandaFay
learn_profile: YolandaFay
email_username: yolandafay@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
